language: julia
julia:
    - nightly
before_install:
    - sudo add-apt-repository ppa:ska-sa/main -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libcasacore-dev -y
    - sudo apt-get install casacore-data -y
    - julia -e "Pkg.clone(\"https://github.com/mweastwood/CasaCore.jl.git\")"
    - julia -e "Pkg.build(\"CasaCore\")"

