site_name: TTCal
repo_url: https://github.com/mweastwood/TTCal.jl
site_description: A calibration routine developed for the OVRO LWA.
site_author: Michael Eastwood

markdown_extensions:
    - math
    - smarty
    - admonition
    - codehilite(css_class=code)
    - toc:
        permalink: ¶
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - mathjaxhelper.js
extra_css:
    - mathjaxstyle.css

pages:
    - Home: index.md
    - Cookbook: cookbook.md
    - Calibration: calibration.md
    - Sky Models: sourcemodel.md
    - Beam Models: beammodel.md
    - The Ionosphere: ionosphere.md
    - Developer Documentation:
        - Building this Website: website.md

theme: material
extra:
    logo: ttcal.png
    version: v0.2.0
    palette:
        primary: 'deep purple'
        accent: 'deep purple'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    author:
        github: 'mweastwood'

